[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jb3"
version = "0.1.0"
description = "JB3 package â€“ unified access to LJSE and NASDAQ financial data"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
  { name = "Janez Bucar", email = "gospod.bucarrr@gmail.com" }
]
dependencies = [
  "pandas",
  "requests",
  "tqdm",
  "ljse"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]